name: Singularity OS Desktop
id: desktop
stages:
  - id: build
    base: ghcr.io/vanilla-os/core:main
    singlelayer: false
    labels:
      maintainer: self-maintained
    args:
      DEBIAN_FRONTEND: noninteractive

    runs:
      commands:
        - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

    modules:
      - name: init-setup
        type: shell
        commands:
          - echo 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"' > /etc/environment
          - sed -i '4,10d' /etc/profile
          - apt update
          - apt upgrade -y
          - apt clean
          - apt-mark hold snapd gnome-software-plugin-snap
          - apt -y install squashfs-tools minisign

      - name: vanilla-tools
        type: shell
        source:
          type: tar
          url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/v1.0.0/vanilla-tools.tar.gz
          checksum: 0e1d92d9c9154f9a115e97b40ff692afa52ddd0d9f770a8ec67440bf1a48aa72
        commands:
          - mkdir -p /usr/bin
          - cp /sources/vanilla-tools/vanilla-tools/lpkg /usr/bin/lpkg
          - cp /sources/vanilla-tools/vanilla-tools/cur-gpu /usr/bin/cur-gpu
          - chmod +x /usr/bin/lpkg
          - chmod +x /usr/bin/cur-gpu

      - name: packages-modules
        type: includes
        includes:
          - modules/00-vanilla-desktop-base.yml
          - modules/00-vanilla-backgrounds.yml
          - modules/00-vanilla-first-setup.yml
          - modules/00-vanilla-system-operator.yml
          - modules/00-vanilla-apx-gui.yml
          - modules/00-vanilla-tour.yml
          - modules/00-vanilla-sideload.yml
          - modules/00-vanilla-updates-utility.yml
          - modules/00-vanilla-prime-utility.yml
          - modules/01-cosmic.yml
          - modules/02-waydroid-modules.yml
          - modules/03-fswarn.yml
          - modules/10-vanilla-abroot-rollback-notifier.yml
          - modules/50-laptop-goodies.yml
          - modules/60-media.yml
          - modules/80-printers.yml
          - modules/90-3d-utils.yml
          - modules/100-accessibility.yml
          - modules/110-fonts.yml
          - modules/121-disable-ssh-daemon.yml
          - modules/130-plymouth.yml
          - modules/131-plymouth-theme-singularity.yml
          - modules/140-password.yml
          - modules/160-utilities.yml
          - modules/210-libs-extra.yml
          - modules/300-hide-image-magick.yml
          - modules/900-kernel.yml
          - modules/997-ensure-exec-hooks.yml
          - modules/998-vanilla-cleanup.yml
          - modules/999-pkg-cleanup.yml
          - modules/999-clear-first-setup-steps-unit.yml

      - name: apx-vso-pico-shutdown-service
        type: shell
        commands:
          - mkdir -p /etc/systemd/user/graphical-session.target.wants/
          - ln -s /etc/systemd/user/apx-vso-pico.service /etc/systemd/user/graphical-session.target.wants/

      - name: set-image-name-abroot
        type: includes
        includes:
          - modules/80-set-image-abroot-config.yml

      - name: cleanup
        type: shell
        commands:
          - apt-get autoremove -y
          - apt-get clean
          - lpkg --lock

      - name: sysconf-setup
        type: shell
        commands:
          - rsync -a /etc/ /sysconf/

      - name: fsguard
        type: fsguard
        CustomFsGuard: false
        FsGuardLocation: "/usr/sbin/FsGuard"
        GenerateKey: true
        FilelistPaths: ["/usr/bin"]
        modules:
          - name: remove-prev-fsguard
            type: shell
            commands:
              - rm -rf /FsGuard
              - rm -f ./minisign.pub ./minisign.key
              - chmod +x /usr/sbin/init

      - name: cleanup2
        type: shell
        commands:
          - rm -rf /tmp/*
          - rm -rf /var/tmp/*
          - rm -rf /sources
